version: 0.0
os: linux
files:
  - source: /
    destination: /POKEMEDI-Server
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: script/deploy.sh
      timeout: 60
      runas: ubuntu
