name: pokemedi main server CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  #S3
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }},
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generate application.properties
      run: |
        mkdir -p src/main/resources
        cat <<EOF > src/main/resources/application.properties
        spring.security.oauth2.client.registration.kakao.client-name=${{ secrets.CLIENT_NAME }}
        spring.security.oauth2.client.registration.kakao.client-id=${{ secrets.CLIENT_ID }}
        spring.security.oauth2.client.registration.kakao.client-secret=${{ secrets.CLIENT_SECRET }}
        spring.security.oauth2.client.registration.kakao.redirect-uri=${{ secrets.KAKAO_LOGIN_REDIRECT_URL }}
        spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code
        spring.security.oauth2.client.registration.kakao.scope=${{ secrets.SCOPE }}
        spring.security.oauth2.client.registration.kakao.client-authentication-method=${{ secrets.CLIENT_AUTHENTICATION_METHOD }}
        spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
        spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
        spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
        spring.security.oauth2.client.provider.kakao.user-name-attribute=${{ secrets.USER_NAME_ATTRIBUTE }}
        spring.datasource.driver-class-name=${{ secrets.DRIVER_CLASS_NAME }}
        spring.datasource.url=${{ secrets.DATASOURCE_URL }}
        spring.datasource.username=${{ secrets.DATASOURCE_USERNAME }}
        spring.datasource.password=${{ secrets.DATASOURCE_PASSWORD }}
        spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
        spring.jackson.time-zone=Asia/Seoul
        spring.jpa.hibernate.ddl-auto=update
        spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        spring.jwt.secret=${{ secrets.JWT_SECRET }}
        redirectURL=${{ secrets.REDIRECT_URL }}
        corsURL=${{ secrets.CORSURL }}
        openai.api_key=${{ secrets.OPENAI_API_KEY }}
        openai.model=${{ secrets.OPENAI_MODEL }}
        openai.url=${{ secrets.OPENAI_URL }}
        spring.cloud.aws.credentials.access-key=${{ secrets.AWS_ACCESS_KEY_FOR_IMAGE_UPLOAD }}
        spring.cloud.aws.credentials.secret-key=${{ secrets.AWS_SECRET_KEY_FOR_IMAGE_UPLOAD }}
        spring.cloud.aws.region.static=${{ secrets.AWS_REGION_FOR_IMAGE_UPLOAD }}
        aws.s3.bucket=${{ secrets.AWS_S3_BUCKET_NAME_FOR_IMAGE_UPLOAD }}
        aws.s3.file.max-size=${{ secrets.AWS_S3_FILE_MAX_SIZE_FOR_IMAGE_UPLOAD }}
        EOF
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew clean build
      
      # 디렉토리 생성
    - name: Make Directory
      run: mkdir -p deploy

      # deploy.sh 파일 복사
    - name: Copy deploy.sh
      run: cp ./scripts/deploy.sh ./deploy/deploy.sh

      # appspec.yml 파일 복사
    - name: Copy appspec.yml
      run: cp ./appspec.yml ./deploy/appspec.yml 
        
    # Jar 파일 복사
    - name: Copy Jar
      run: cp ./build/libs/*.jar ./deploy
    - name: Make zip file
      run: zip -r ./pokemedi_jar.zip ./deploy  
      shell: bash
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./pokemedi_jar.zip s3://${{ secrets.S3_BUCKET_NAME }}/deploy/pokemedi_jar.zip

# Deploy
    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: 
        aws deploy create-deployment 
        --application-name pokemedi
        --deployment-group-name pokemedi-group
        --file-exists-behavior OVERWRITE 
        --s3-location bucket=${{ secrets.S3_BUCKET_NAME }},bundleType=zip,key=deploy/pokemedi_jar.zip
        --region ap-northeast-2
      
